### ISSUE TITLE
This work implicitly promotes misleading solutions

### ISSUE THREAD

**Issue by ddebernardy** [ed-hawkins/climate-visuals#3]
These charts and messaging build around the incorrect notion that fossil fuels are the source of the CO2 in the atmosphere.

To cut a long story short, the latter derives from an accounting chicanery in climate agreements. Natural and industrial emissions get counted differently. The first are treated as a carbon stock whose value changes when land use changes only. The other gets treated as a flow.

This puts the spotlight on fossil fuel while ignoring soil damage from tilling, harvesting, or forest clear cuts. The latter produce massive emissions. There is ample evidence in the scientific literature that shows that these emissions go away when farms keep hedgerows around and when loggers thin forests instead of clearing them. Which makes sense: the perennials left behind basically soak up the soil emissions tied to the soil disturbances.

These avoidable emissions are an order of magnitude greater than energy emissions as you no doubt know. It follows that the hockey stick is soil, not oil.

The immediate corollary is that the solutions are trivial: put the hedgerows back in by prompting farmers to switch to on-contour alley cropping (profitable), and prompt loggers to switch back to forest thinning (also profitable).

**Comment by ed-hawkins** [comment]
This comment is not correct. Please read the IPCC 6th Assessment Report for a summary of the latest science which clearly identifies the burning of fossil fuels as the dominant reason for increasing atmospheric CO2 levels.
